In [24]:
import pandas as pd
import random
import math
import numpy as np
from sklearn.datasets import load_iris
from icecream import ic

In [25]:
data = load_iris()

In [26]:
X_train = data.data
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Нормализация данных
X_train = scaler.fit_transform(X_train)
X_train

array([[-2.0449e+00, -1.2465e+00, -1.9860e-01,  4.0020e-01],
       [-1.9451e+00, -9.9700e-01, -1.9860e-01,  4.0020e-01],
       [-1.8453e+00, -1.0968e+00, -1.4870e-01,  4.0020e-01],
       [-1.7954e+00, -1.0469e+00, -2.4850e-01,  4.0020e-01],
       [-1.9950e+00, -1.2964e+00, -1.9860e-01,  4.0020e-01],
       [-2.1946e+00, -1.4461e+00, -3.4830e-01,  3.0040e-01],
       [-1.7954e+00, -1.1966e+00, -1.9860e-01,  3.5030e-01],
       [-1.9950e+00, -1.1966e+00, -2.4850e-01,  4.0020e-01],
       [-1.6956e+00, -9.4710e-01, -1.9860e-01,  4.0020e-01],
       [-1.9451e+00, -1.0469e+00, -2.4850e-01,  4.5010e-01],
       [-2.1946e+00, -1.3463e+00, -2.4850e-01,  4.0020e-01],
       [-1.8952e+00, -1.1966e+00, -2.9840e-01,  4.0020e-01],
       [-1.8952e+00, -9.9700e-01, -1.9860e-01,  4.5010e-01],
       [-1.6457e+00, -9.9700e-01, -4.8900e-02,  4.5010e-01],
       [-2.3942e+00, -1.4960e+00, -9.8800e-02,  4.0020e-01],
       [-2.3443e+00, -1.6956e+00, -2.4850e-01,  3.0040e-01],
       [-2.1946e+00, -1.

In [28]:
y_train_data = data.target
y_train_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
y_train = []
for i in y_train_data:
    if i == 0:
        y_train.append([1, 0, 0])
    if i == 1:
        y_train.append([0, 1, 0])
    if i == 2:
        y_train.append([0, 0, 1])
y_train

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0,

In [30]:
def breaks_f():
    ic(1)
    ic(2)
    exit(123)

In [31]:
class CounterPropagation:
    def __init__(self, kohonen_neurons, grossberg_neurons, epoch, learning_rate_a, learning_rate_b):
        self.kohonen_neurons = kohonen_neurons
        self.grossberg_neurons = grossberg_neurons
        self.epoch = epoch
        self.learning_rate_a = learning_rate_a
        self.learning_rate_b = learning_rate_b

    def get_weight_w(self, X_train):
        mass_weight = []
        size = self.kohonen_neurons
        for i in range(size):
            vector = []
            for j in range(size):
                vector.append(1/2)
            mass_weight.append(vector)
        return mass_weight

    def get_weight_v(self, y_train):
        mass_weight = []
        size = self.grossberg_neurons
        for i in range(size):
            vector = []
            for j in range(self.kohonen_neurons):
                vector.append(random.uniform(0, 0.25))
            mass_weight.append(vector)
        return mass_weight

    def count_layer_kohonen(self, X_train, i):
        result_kohonen_layer = []
        # ic(X_train[i])
        # ic(self.vector_weight_w[0])
        # ic(np.dot(X_train[i], self.vector_weight_w))
        for j, jj in enumerate(self.vector_weight_w):
            value = 0
            for index, index_value in enumerate(X_train[i]):
                value += X_train[i][index] * self.vector_weight_w[j][index]
            result_kohonen_layer.append(value)
        # ic(result_kohonen_layer)
        for i, ii in enumerate(result_kohonen_layer):
            if i != np.argmax(result_kohonen_layer):
                result_kohonen_layer[i] = 0

        return result_kohonen_layer, np.argmax(result_kohonen_layer)

    def count_layer_grossberg(self, X_train, i, kohonen_layer):
        # ic(kohonen_layer)
        # ic(self.vector_weight_v)
        # ic(np.multiply(kohonen_layer, self.vector_weight_v))
        result_layer_grossberg = []
        for j, jj in enumerate(self.vector_weight_v):
            value = 0
            for index, index_value in enumerate(kohonen_layer):
                value += kohonen_layer[index] * self.vector_weight_w[j][index]
            result_layer_grossberg.append(value)
        # ic(result_layer_grossberg)
        return result_layer_grossberg

    def weight_adjustment_kh(self, result_kohonen_layer, X_train, y_train):
        for i, ii in enumerate(self.vector_weight_w):
            for j, ii in enumerate(self.vector_weight_w[i]):
                self.vector_weight_w[i][j] += self.learning_rate_a * (result_kohonen_layer[i] - self.vector_weight_w[i][j])
        
        
        
    def weight_adjustment_gr(self, result_kohonen_layer, result_layer_grossberg, X_train, y_train):
        # ic(self.vector_weight_v)

        for i, ii in enumerate(self.vector_weight_v):
            for j, jj in enumerate(ii):
                # ic(self.learning_rate)
                # ic(y_train[i])
                # ic(result_layer_grossberg[i])
                # ic(result_kohonen_layer[j])
                if result_kohonen_layer[j] != 0:
                    self.vector_weight_v[i][j] += self.learning_rate_b * (y_train[i] - result_layer_grossberg[i]) * \
                                                  result_kohonen_layer[j]
                else:
                    self.vector_weight_v[i][j] += self.learning_rate_b * (y_train[i] - result_layer_grossberg[i])

    def train(self, X_train, y_train):
        self.vector_weight_w = self.get_weight_w(X_train=X_train)
        self.vector_weight_v = self.get_weight_v(y_train=y_train)
        # ic(self.vector_weight_w)
        for e in range(self.epoch):
            for i in range(X_train.shape[0]):
                result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_train, i)
                self.weight_adjustment_kh(result_kohonen_layer, X_train[i], y_train[i])
                result_layer_grossberg = self.count_layer_grossberg(X_train, i, result_kohonen_layer)
                self.weight_adjustment_gr(result_kohonen_layer, result_layer_grossberg, X_train[i], y_train[i])
            self.learning_rate_b *= 0.9
            # ic(self.vector_weight_w)
            # ic(self.vector_weight_v)

    def predict(self, X_test):
        predictions = []
        for i in range(X_test.shape[0]):
            result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_test, i)
            result_layer_grossberg = self.count_layer_grossberg(X_test, i, result_kohonen_layer)
            predictions.append(result_layer_grossberg)
        return predictions



In [32]:
cp_neurons = CounterPropagation(kohonen_neurons=4, grossberg_neurons=3, epoch=10, learning_rate_a=0.001, learning_rate_b=0.1)
cp_neurons.train(X_train=X_train, y_train=y_train)

In [33]:
x_test_pred = cp_neurons.predict(X_test=X_train)
x_test_pred

[[-3.764601413560612e-78, -5.177475815971597e-46, -5.177475815971597e-46],
 [-3.3390155265269137e-78, -4.592165341986589e-46, -4.592165341986589e-46],
 [-3.2782175426649566e-78, -4.50854955998873e-46, -4.50854955998873e-46],
 [-3.2782175426649556e-78, -4.508549559988729e-46, -4.508549559988729e-46],
 [-3.764601413560612e-78, -5.177475815971597e-46, -5.177475815971597e-46],
 [-4.494177219904096e-78, -6.180865199945898e-46, -6.180865199945898e-46],
 [-3.4606114942508265e-78, -4.7593969059823045e-46, -4.7593969059823045e-46],
 [-3.703803429698655e-78, -5.093860033973739e-46, -5.093860033973739e-46],
 [-2.974227623355172e-78, -4.090470649999439e-46, -4.090470649999439e-46],
 [-3.399813510388871e-78, -4.6757811239844474e-46, -4.6757811239844474e-46],
 [-4.1293893167323534e-78, -5.679170507958746e-46, -5.679170507958746e-46],
 [-3.6430054458366983e-78, -5.01024425197588e-46, -5.01024425197588e-46],
 [-3.2174195588029995e-78, -4.4249337779908716e-46, -4.4249337779908716e-46],
 [-2.73103568790

In [34]:
x_test_pred_norm = x_test_pred
for i, ii in enumerate(x_test_pred_norm):
    print(x_test_pred_norm)
    # print(x_test_pred_norm[i])
    for j, jj in enumerate(x_test_pred_norm[i]):
        if jj != max(x_test_pred_norm[i]):
            x_test_pred_norm[i][j] = 0
        else:
            x_test_pred_norm[i][j] = 1
x_test_pred_norm

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1,