In [149]:
import pandas as pd
import random
import math
import numpy as np
from sklearn.datasets import load_iris
from icecream import ic

In [150]:
data = load_iris()

In [151]:
X_train = data.data
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [152]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Нормализация данных
X_train = scaler.fit_transform(X_train)
X_train

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [153]:
y_train_data = data.target
y_train_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [165]:
y_train = []
for i in y_train_data:
    if i == 0:
        y_train.append([1, 0, 0])
    if i == 1:
        y_train.append([0, 1, 0])
    if i == 2:
        y_train.append([0, 0, 1])
y_train

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0,

In [155]:
def breaks_f():
    ic(1)
    ic(2)
    exit(123)

In [162]:
class CounterPropagation:
    def __init__(self, kohonen_neurons, grossberg_neurons, epoch, learning_rate_a, learning_rate_b):
        self.kohonen_neurons = kohonen_neurons
        self.grossberg_neurons = grossberg_neurons
        self.epoch = epoch
        self.learning_rate_a = learning_rate_a
        self.learning_rate_b = learning_rate_b

    def get_weight_w(self, X_train):
        mass_weight = []
        size = self.kohonen_neurons
        for i in range(size):
            vector = []
            for j in range(size):
                vector.append(1 / (math.sqrt(X_train[0].shape[0])))

            mass_weight.append(vector)
        return mass_weight

    def get_weight_v(self, y_train):
        mass_weight = []
        for i in range(self.grossberg_neurons):
            vector = []
            for j in range(self.kohonen_neurons):
                vector.append(1 / (math.sqrt(len(y_train[0]))))
            mass_weight.append(vector)
        print(mass_weight)
        return mass_weight

    def count_layer_kohonen(self, X_train, i):
        result_kohonen_layer = []
        for j, jj in enumerate(self.vector_weight_w):
            value = 0
            for index, index_value in enumerate(X_train[i]):
                value += X_train[i][index] * self.vector_weight_w[j][index]
            result_kohonen_layer.append(value)
        for i, ii in enumerate(result_kohonen_layer):
            if i != np.argmax(result_kohonen_layer):
                result_kohonen_layer[i] = 0
        return result_kohonen_layer, np.argmax(result_kohonen_layer)

    def count_layer_grossberg(self, X_train, i, kohonen_layer):
        result_layer_grossberg = []
        for j, jj in enumerate(self.vector_weight_v):
            value = 0
            for index, index_value in enumerate(kohonen_layer):
                value += kohonen_layer[index] * self.vector_weight_w[j][index]
            result_layer_grossberg.append(value)
        print(result_layer_grossberg)
        return result_layer_grossberg

    def weight_adjustment_kh(self, result_kohonen_layer, X_train, index_winning_neuron):
        for i, ii in enumerate(self.vector_weight_w):
            for j, jj in enumerate(self.vector_weight_w[i]):
                self.vector_weight_w[i][j] += self.learning_rate_a * (
                        X_train[i] - self.vector_weight_w[i][j])

    def weight_adjustment_gr(self, result_kohonen_layer, result_layer_grossberg, index_winning_neuron, y_train):
        for j, jj in enumerate(y_train):
            self.vector_weight_v[index_winning_neuron][j] += self.learning_rate_b * (
                    y_train[j] - result_layer_grossberg[j]) * result_kohonen_layer[index_winning_neuron]

    def train(self, X_train, y_train):
        self.vector_weight_w = self.get_weight_w(X_train=X_train)
        self.vector_weight_v = self.get_weight_v(y_train=y_train)
        for e in range(self.epoch):
            for i in range(X_train.shape[0]):
                result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_train, i)
                result_layer_grossberg = self.count_layer_grossberg(X_train, i, result_kohonen_layer)
                self.weight_adjustment_kh(result_kohonen_layer, X_train[i], index_winning_neuron)
                self.weight_adjustment_gr(result_kohonen_layer, result_layer_grossberg, index_winning_neuron,
                                          y_train[i])
            self.learning_rate_a *= 0.9
            self.learning_rate_b *= 0.9

    def predict(self, X_test):
        predictions = []
        for i in range(X_test.shape[0]):
            result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_test, i)
            result_layer_grossberg = self.count_layer_grossberg(X_test, i, result_kohonen_layer)
            predictions.append(result_layer_grossberg)
        return predictions



In [163]:
cp_neurons = CounterPropagation(kohonen_neurons=4, grossberg_neurons=3, epoch=1000, learning_rate_a=0.2,
                                learning_rate_b=0.1)
cp_neurons.train(X_train=X_train, y_train=y_train)

[[0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258], [0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258], [0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258]]
[0.23917137476459507, 0.23917137476459507, 0.23917137476459507]
[0.16165254237288137, 0.19095206567796613, 0.15041906061476587]
[0.13772812478203253, 0.17825954436074498, 0.12197442837839276]
[0.11194036409290647, 0.16880606905210294, 0.09594237849915412]
[0.13579306261770244, 0.23666334466101696, 0.11766313180886716]
[0.1881402665550673, 0.374340877809751, 0.1487544406550863]
[0.1299842991111111, 0.27608665131199994, 0.09108909669749149]
[0.12382694087065352, 0.30573677896371043, 0.08776257693271806]
[0.0677467449904961, 0.17342516035131053, 0.04485227279025777]
[0.07188600347696333, 0.20733639244712299, 0.05138323100092985]
[0.1095061596470355, 0.3131679423417862, 0.07416401320690134]
[0.10084660200950907, 0.272332492216053, 0.05643376041819

IndexError: list index out of range

In [158]:
x_test_pred_norm = cp_neurons.predict(X_test=X_train)

In [159]:
x_test_pred_norm = x_test_pred_norm
for i, ii in enumerate(x_test_pred_norm):
    # print(x_test_pred_norm)
    # print(x_test_pred_norm[i])
    for j, jj in enumerate(x_test_pred_norm[i]):
        if jj != max(x_test_pred_norm[i]):
            x_test_pred_norm[i][j] = 0
        else:
            x_test_pred_norm[i][j] = 1
x_test_pred_norm

[[0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 0, 1,