In [107]:
import pandas as pd
import random
import math
import numpy as np
from sklearn.datasets import load_iris
from icecream import ic

In [108]:
data = load_iris()

In [109]:
X_train = data.data
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [122]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Нормализация данных
X_train = scaler.fit_transform(X_train)
# X_train = X_train.to_numpy()
X_train[5]

array([0.30555556, 0.79166667, 0.11864407, 0.125     ])

In [111]:
y_train_data = data.target
y_train_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [112]:
y_train = []
for i in y_train_data:
    if i == 0:
        y_train.append([1, 0, 0])
    if i == 1:
        y_train.append([0, 1, 0])
    if i == 2:
        y_train.append([0, 0, 1])
y_train

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0,

In [113]:
class CounterPropagation:
    def __init__(self, kohonen_neurons, grossberg_neurons, epoch, learning_rate_a, learning_rate_b):
        self.kohonen_neurons = kohonen_neurons
        self.grossberg_neurons = grossberg_neurons
        self.epoch = epoch
        self.learning_rate_a = learning_rate_a
        self.learning_rate_b = learning_rate_b

    def get_weight_w(self):
        mass_weight = []
        size = self.kohonen_neurons
        for i in range(size):
            vector = []
            for j in range(size):
                # vector.append(1 / (math.sqrt(size)))
                vector.append(1 / size)
                # vector.append(random.uniform(0.0, 1))
            mass_weight.append(vector)
        return mass_weight

    def get_weight_v(self):
        mass_weight = []
        for i in range(self.kohonen_neurons):
            vector = []
            for j in range(self.grossberg_neurons):
                vector.append(1 / (math.sqrt(len(y_train[0]))))
            mass_weight.append(vector)
        return mass_weight

    def count_layer_kohonen(self, training_example):
        result_kohonen_layer = [0] * self.kohonen_neurons
        for i, ii in enumerate(self.vector_weight_w):
            for j, jj in enumerate(self.vector_weight_w[i]):
                result_kohonen_layer[j] += training_example[j] * self.vector_weight_w[i][j]
        for i, ii in enumerate(result_kohonen_layer):
            if i != np.argmax(result_kohonen_layer):
                result_kohonen_layer[i] = 0
        # print(result_kohonen_layer)
        return result_kohonen_layer, np.argmax(result_kohonen_layer)

    def count_layer_grossberg(self, kohonen_layer, index_winning_neuron):
        result_layer_grossberg = []
        for j, jj in enumerate(self.vector_weight_v[index_winning_neuron]):
            value = kohonen_layer[j] * self.vector_weight_w[index_winning_neuron][j]
            result_layer_grossberg.append(value)
        return result_layer_grossberg

    def weight_adjustment_kh(self, result_kohonen_layer, X_train, index_winning_neuron):
        # print(self.vector_weight_w)
        for j, jj in enumerate(self.vector_weight_w[index_winning_neuron]):
            self.vector_weight_w[index_winning_neuron][j] = (self.vector_weight_w[index_winning_neuron][j] +
                                                             self.learning_rate_a * (X_train[j] - self.vector_weight_w[
                        index_winning_neuron][j]))
        # print(self.vector_weight_w)
        # exit(123)

    def weight_adjustment_gr(self, result_kohonen_layer, result_layer_grossberg, index_winning_neuron, y_train):
        for j, jj in enumerate(y_train):
            self.vector_weight_v[index_winning_neuron][j] += self.learning_rate_b * (
                    y_train[j] - result_layer_grossberg[j]) * result_kohonen_layer[index_winning_neuron]

    def train(self, X_train, y_train):
        self.vector_weight_w = self.get_weight_w()
        self.vector_weight_v = self.get_weight_v()
        for eph in range(self.epoch):
            for index_training_example, training_example in enumerate(X_train):
                result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(training_example)
                # result_layer_grossberg = self.count_layer_grossberg(result_kohonen_layer, index_winning_neuron)
                self.weight_adjustment_kh(result_kohonen_layer, training_example, index_winning_neuron)
                # self.weight_adjustment_gr(result_kohonen_layer, result_layer_grossberg, index_winning_neuron,
                #                           y_train[training_example])
                self.learning_rate_a = self.learning_rate_a * 0.99
        # self.learning_rate_b *= 0.95

    def predict(self, X_test):
        predictions = []
        for training_example in range(len(X_test)):
            result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_test[training_example])
            # result_layer_grossberg = self.count_layer_grossberg(result_kohonen_layer, index_winning_neuron)
            predictions.append([result_kohonen_layer, index_winning_neuron])
        return predictions


In [114]:
cp_neurons = CounterPropagation(kohonen_neurons=4, grossberg_neurons=3, epoch=10, learning_rate_a=0.7, learning_rate_b=0.1)

In [115]:
cp_neurons.train(X_train=X_train, y_train=y_train)

In [116]:
# x_test_pred_norm = cp_neurons.predict(X_test=X_train)
print(cp_neurons.predict(X_test=[[5.1, 3.5, 1.4, 0.2]]))
print(cp_neurons.predict(X_test=[[6.9, 3.1, 4.9, 1.5]]))
print(cp_neurons.predict(X_test=[[5.7, 2.5, 5.0, 2.0]]))

[[[10.281274837075863, 0, 0, 0], 0]]
[[[13.909960073690876, 0, 0, 0], 0]]
[[[11.490836582614198, 0, 0, 0], 0]]


In [117]:
X_train

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [118]:
x_test_pred_norm = x_test_pred_norm
for i, ii in enumerate(x_test_pred_norm):
    for j, jj in enumerate(x_test_pred_norm[i]):
        if jj != max(x_test_pred_norm[i]):
            x_test_pred_norm[i][j] = 0
        else:
            x_test_pred_norm[i][j] = 1
x_test_pred_norm

NameError: name 'x_test_pred_norm' is not defined

In [ ]:
# ic(cp_neurons.get_weight_w(X_train=X_train))

In [ ]:
# ic(cp_neurons.get_weight_v(y_train=y_train))