In [154]:
import pandas as pd
import random
import math
import numpy as np
from sklearn.datasets import load_iris
from icecream import ic

In [155]:
data = load_iris()

In [156]:
X_train = data.data
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [157]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Нормализация данных
X_train = scaler.fit_transform(X_train)
X_train

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [158]:
y_train_data = data.target
y_train_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [159]:
y_train = []
for i in y_train_data:
    if i == 0:
        y_train.append([1, 0, 0])
    if i == 1:
        y_train.append([0, 1, 0])
    if i == 2:
        y_train.append([0, 0, 1])
y_train

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0,

In [160]:
def breaks_f():
    ic(1)
    ic(2)
    exit(123)

In [169]:
class CounterPropagation:
    def __init__(self, kohonen_neurons, grossberg_neurons, epoch, learning_rate_a, learning_rate_b):
        self.kohonen_neurons = kohonen_neurons
        self.grossberg_neurons = grossberg_neurons
        self.epoch = epoch
        self.learning_rate_a = learning_rate_a
        self.learning_rate_b = learning_rate_b

    def get_weight_w(self, X_train):
        mass_weight = []
        size = self.kohonen_neurons
        for i in range(size):
            vector = []
            for j in range(size):
                vector.append(1/2)
            mass_weight.append(vector)
        return mass_weight

    def get_weight_v(self, y_train):
        mass_weight = []
        size = self.grossberg_neurons
        for i in range(size):
            vector = []
            for j in range(self.kohonen_neurons):
                vector.append(random.uniform(0, 0.25))
            mass_weight.append(vector)
        return mass_weight

    def count_layer_kohonen(self, X_train, i):
        result_kohonen_layer = []
        # ic(X_train[i])
        # ic(self.vector_weight_w[0])
        # ic(np.dot(X_train[i], self.vector_weight_w))
        for j, jj in enumerate(self.vector_weight_w):
            value = 0
            for index, index_value in enumerate(X_train[i]):
                value += X_train[i][index] * self.vector_weight_w[j][index]
            result_kohonen_layer.append(value)
        # ic(result_kohonen_layer)
        for i, ii in enumerate(result_kohonen_layer):
            if i != np.argmax(result_kohonen_layer):
                result_kohonen_layer[i] = 0

        return result_kohonen_layer, np.argmax(result_kohonen_layer)

    def count_layer_grossberg(self, X_train, i, kohonen_layer):
        # ic(kohonen_layer)
        # ic(self.vector_weight_v)
        # ic(np.multiply(kohonen_layer, self.vector_weight_v))
        result_layer_grossberg = []
        for j, jj in enumerate(self.vector_weight_v):
            value = 0
            for index, index_value in enumerate(kohonen_layer):
                value += kohonen_layer[index] * self.vector_weight_w[j][index]
            result_layer_grossberg.append(value)
        # ic(result_layer_grossberg)
        return result_layer_grossberg

    def weight_adjustment_kh(self, result_kohonen_layer, X_train, y_train):
        for i, ii in enumerate(self.vector_weight_w):
            for j, ii in enumerate(self.vector_weight_w[i]):
                self.vector_weight_w[i][j] += self.learning_rate_a * (result_kohonen_layer[i] - self.vector_weight_w[i][j])
        
        
        
    def weight_adjustment_gr(self, result_kohonen_layer, result_layer_grossberg, X_train, y_train):
        # ic(self.vector_weight_v)

        for i, ii in enumerate(self.vector_weight_v):
            for j, jj in enumerate(ii):
                # ic(self.learning_rate)
                # ic(y_train[i])
                # ic(result_layer_grossberg[i])
                # ic(result_kohonen_layer[j])
                if result_kohonen_layer[j] != 0:
                    self.vector_weight_v[i][j] += self.learning_rate_b * (y_train[i] - result_layer_grossberg[i]) * \
                                                  result_kohonen_layer[j]
                else:
                    self.vector_weight_v[i][j] += self.learning_rate_b * (y_train[i] - result_layer_grossberg[i])

    def train(self, X_train, y_train):
        self.vector_weight_w = self.get_weight_w(X_train=X_train)
        self.vector_weight_v = self.get_weight_v(y_train=y_train)
        # ic(self.vector_weight_w)
        for e in range(self.epoch):
            for i in range(X_train.shape[0]):
                result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_train, i)
                self.weight_adjustment_kh(result_kohonen_layer, X_train[i], y_train[i])
                result_layer_grossberg = self.count_layer_grossberg(X_train, i, result_kohonen_layer)
                self.weight_adjustment_gr(result_kohonen_layer, result_layer_grossberg, X_train[i], y_train[i])
            self.learning_rate_b *= 0.9
            # ic(self.vector_weight_w)
            # ic(self.vector_weight_v)

    def predict(self, X_test):
        predictions = []
        for i in range(X_test.shape[0]):
            result_kohonen_layer, index_winning_neuron = self.count_layer_kohonen(X_test, i)
            result_layer_grossberg = self.count_layer_grossberg(X_test, i, result_kohonen_layer)
            predictions.append(result_layer_grossberg)
        return predictions



In [170]:
cp_neurons = CounterPropagation(kohonen_neurons=4, grossberg_neurons=3, epoch=10, learning_rate_a=0.001, learning_rate_b=0.1)
cp_neurons.train(X_train=X_train, y_train=y_train)

In [171]:
x_test_pred = cp_neurons.predict(X_test=X_train)
x_test_pred

[[0.024870881741486932, 0.024911492334254295, 0.33190227769942376],
 [0.018472814778696604, 0.018502978243186613, 0.24651998124946337],
 [0.018394635957463525, 0.018424671767119857, 0.24547668374578735],
 [0.017960828828765985, 0.017990156293425697, 0.2396875213190775],
 [0.02515039724237193, 0.025191464243975, 0.33563241611431055],
 [0.03629932324697145, 0.03635859485018344, 0.48441499540889116],
 [0.022004362706430906, 0.02204029268359314, 0.29364853958539383],
 [0.02379986478978633, 0.023838726565051985, 0.3176095409392645],
 [0.013907165456355591, 0.013929873868496617, 0.18559132479841084],
 [0.018404765452209006, 0.018434817801881505, 0.2456118620001378],
 [0.029638900750806677, 0.029687296836678274, 0.3955315605594516],
 [0.023008363338970727, 0.023045932705570378, 0.30704694259399207],
 [0.016059328854502272, 0.016085551441662883, 0.21431197657307965],
 [0.010575921200946388, 0.010593190167664, 0.14113582187592646],
 [0.033566307242817804, 0.03362111622178008, 0.4479428571792901

In [172]:
x_test_pred_norm = x_test_pred
for i, ii in enumerate(x_test_pred_norm):
    print(x_test_pred_norm)
    # print(x_test_pred_norm[i])
    for j, jj in enumerate(x_test_pred_norm[i]):
        if jj != max(x_test_pred_norm[i]):
            x_test_pred_norm[i][j] = 0
        else:
            x_test_pred_norm[i][j] = 1
x_test_pred_norm

[[0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0,