In [131]:
import pandas as pd
import math
import numpy as np

In [132]:
data = pd.read_csv('../Datasets/iris/iris.csv')
data = data.sample(frac=1, random_state=12).reset_index(drop=True)
X_train = data.drop(['Species', 'Id'], axis=1)
y_train = pd.DataFrame(data['Species'])
y_train['Species'] = y_train['Species'].replace('Iris-setosa', 2)
y_train['Species'] = y_train['Species'].replace('Iris-versicolor', 1)
y_train['Species'] = y_train['Species'].replace('Iris-virginica', 0)
X_train = X_train.to_numpy()
y_train_new = y_train.to_numpy()

In [133]:
X_train

array([[5. , 3.5, 1.3, 0.3],
       [6.3, 2.5, 5. , 1.9],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 2

In [134]:
y_train_new

array([[2],
       [0],
       [2],
       [1],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [1],
       [1],
       [1],
       [2],
       [0],
       [1],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [2],
       [0],
       [0],
       [2],
       [1],
       [2],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
    

In [135]:
def convert_answer(input_answer):
    y_convert = []
    for i in input_answer:
        if i == 0:
            y_convert.append([1, 0, 0])
        if i == 1:
            y_convert.append([0, 1, 0])
        if i == 2:
            y_convert.append([0, 0, 1])
    return y_convert

In [136]:
y_train = convert_answer(y_train_new)
y_train

[[0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0,

In [137]:
def get_norm_value(input_vector):
    norm = np.linalg.norm(input_vector)  # Вычисление длины вектора
    return norm  # Нормализация вектора


def normalize_data(input_vector, norm):
    return input_vector / norm


# Нормализация входного вектора
norm_value = get_norm_value(input_vector=X_train)
X_train = normalize_data(input_vector=X_train, norm=norm_value)

# print("Входной вектор:", X_train)
print("Нормализованный вектор:", X_train)

Нормализованный вектор: [[0.05120146 0.03584102 0.01331238 0.00307209]
 [0.06451384 0.02560073 0.05120146 0.01945655]
 [0.04505728 0.03072087 0.01331238 0.00204806]
 [0.05836966 0.02867282 0.0419852  0.01331238]
 [0.06963398 0.03276893 0.06041772 0.02355267]
 [0.0665619  0.03072087 0.0563216  0.01843252]
 [0.06348981 0.03481699 0.05529757 0.02355267]
 [0.05222549 0.03481699 0.01536044 0.00204806]
 [0.07885025 0.03072087 0.06246578 0.02355267]
 [0.05222549 0.03379296 0.0174085  0.00512015]
 [0.05734563 0.03072087 0.04608131 0.01536044]
 [0.05529757 0.03993714 0.01331238 0.00409612]
 [0.05529757 0.03481699 0.01536044 0.00409612]
 [0.05222549 0.03788908 0.01536044 0.00409612]
 [0.07168204 0.03276893 0.04812937 0.01433641]
 [0.0737301  0.03276893 0.06144175 0.01843252]
 [0.06860995 0.02560073 0.05939369 0.01843252]
 [0.06041772 0.03072087 0.04300922 0.01536044]
 [0.04710534 0.03481699 0.01433641 0.00307209]
 [0.06451384 0.02560073 0.05017743 0.01536044]
 [0.05017743 0.03072087 0.01433641 0

In [138]:
X_test = pd.read_csv('../Datasets/iris/test_iris.csv')
X_test = X_test.drop(['species', 'Unnamed: 0'], axis=1)
X_test = X_test.to_numpy()
X_test = normalize_data(input_vector=X_test, norm=norm_value)
X_test

array([[0.05939369, 0.02867282, 0.05222549, 0.0245767 ],
       [0.06041772, 0.03276893, 0.0491534 , 0.01843252],
       [0.06144175, 0.03072087, 0.0491534 , 0.01843252],
       [0.05324952, 0.02764879, 0.03993714, 0.01433641],
       [0.05222549, 0.03891311, 0.01945655, 0.00409612],
       [0.0737301 , 0.03276893, 0.06144175, 0.01843252],
       [0.0563216 , 0.03584102, 0.01331238, 0.00204806],
       [0.07065801, 0.0317449 , 0.05222549, 0.02355267],
       [0.0491534 , 0.03072087, 0.01433641, 0.00102403],
       [0.06246578, 0.02969685, 0.04812937, 0.01433641],
       [0.05017743, 0.02560073, 0.04608131, 0.0174085 ],
       [0.05836966, 0.02969685, 0.04300922, 0.01331238],
       [0.06451384, 0.02969685, 0.05734563, 0.01843252],
       [0.04710534, 0.03686505, 0.01024029, 0.00204806],
       [0.05120146, 0.03481699, 0.01638447, 0.00409612],
       [0.0665619 , 0.03072087, 0.05939369, 0.02252864],
       [0.05529757, 0.03072087, 0.04608131, 0.01536044],
       [0.05324952, 0.0419852 ,

In [139]:
y_test = pd.read_csv('../Datasets/iris/test_iris.csv')
y_test = y_test.drop(['Unnamed: 0', 'petal length', 'petal width', 'sepal length', 'sepal width'], axis=1)
y_test['species'] = pd.factorize(y_test['species'])[0]
y_test = y_test.to_numpy()
y_test = convert_answer(y_test)
y_test

[[1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0]]

In [140]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

def count_error(answers_data, predict_data):
    mse = mean_squared_error(answers_data, predict_data)
    r2 = r2_score(answers_data, predict_data)
    mae = mean_absolute_error(answers_data, predict_data)

    print(f'Mean Squared Error: {mse}')
    print(f'R-squared: {r2}')
    print(f'Mean Absolute Error: {mae}')

In [141]:
def bringing_the_response_back_to_normal(input_value_answer):
    for i, ii in enumerate(input_value_answer):
        for j, jj in enumerate(input_value_answer[i]):
            if jj != max(input_value_answer[i]):
                input_value_answer[i][j] = 0
            else:
                input_value_answer[i][j] = 1
    return input_value_answer

In [142]:
class CounterPropagation:
    def __init__(self, kohonen_neurons, grossberg_neurons, epoch, learning_rate_a, learning_rate_b):
        self.kohonen_neurons = kohonen_neurons
        self.grossberg_neurons = grossberg_neurons
        self.epoch = epoch
        self.learning_rate_a = learning_rate_a
        self.learning_rate_b = learning_rate_b
        self.weight_w = self.get_weight_w()
        self.weight_v = self.get_weight_v()

    def get_weight_w(self):
        mass_weight = []
        for i in range(self.kohonen_neurons):
            vector = []
            for j in range(self.kohonen_neurons):
                # vector.append(random.uniform(0, 1))
                vector.append(1 / (math.sqrt(self.kohonen_neurons)))
            mass_weight.append(vector)
        return mass_weight

    def get_weight_v(self):
        mass_weight = []
        for i in range(self.kohonen_neurons):
            vector = []
            for j in range(self.grossberg_neurons):
                vector.append(1 / (math.sqrt(self.grossberg_neurons)))
            mass_weight.append(vector)
        return mass_weight

    def calculation_of_values_on_kohonen_layer(self, example):
        result_kohonen_layer = []
        for i, ii in enumerate(self.weight_w):
            neuron_output = 0
            for index_value, value in enumerate(example):
                neuron_output += value * self.weight_w[i][index_value]
            result_kohonen_layer.append(neuron_output)
        for i, ii in enumerate(result_kohonen_layer):
            if i != np.argmax(result_kohonen_layer):
                result_kohonen_layer[i] = 0
        return result_kohonen_layer, np.argmax(result_kohonen_layer)

    def calculation_of_values_on_grossberg_layer(self, kohonen_layer, index_winning_neuron):
        result_layer_grossberg = []
        for i, ii in enumerate(self.weight_v[index_winning_neuron]):
            value = kohonen_layer[index_winning_neuron] * self.weight_v[index_winning_neuron][i]
            result_layer_grossberg.append(value)
        return result_layer_grossberg

    def weight_adjustment_kh(self, result_kohonen_layer, index_winning_neuron, example):
        for i, ii in enumerate(self.weight_w[index_winning_neuron]):
            self.weight_w[index_winning_neuron][i] += self.learning_rate_a * (
                    example[i] - self.weight_w[index_winning_neuron][i])

    def weight_adjustment_gr(self, result_kohonen_layer, result_layer_grossberg, index_winning_neuron, y):
        for j, jj in enumerate(y):
            self.weight_v[index_winning_neuron][j] += self.learning_rate_b * (
                    y[j] - result_layer_grossberg[j]) * result_kohonen_layer[index_winning_neuron]

    def train(self, X, y):
        for eph in range(self.epoch):
            for index_training_example, training_example in enumerate(X):
                result_kohonen_layer, index_winning_neuron = self.calculation_of_values_on_kohonen_layer(
                    training_example)
                self.weight_adjustment_kh(result_kohonen_layer, index_winning_neuron, training_example)

                result_layer_grossberg = self.calculation_of_values_on_grossberg_layer(result_kohonen_layer,
                                                                                       index_winning_neuron)
                self.weight_adjustment_gr(result_kohonen_layer, result_layer_grossberg, index_winning_neuron,
                                          y_train[index_training_example])
                self.learning_rate_a *= 0.85
                # self.learning_rate_b *= 0.9


    def predict(self, X):
        predictions = []
        for index_training_example, training_example in enumerate(X):
            result_kohonen_layer, index_winning_neuron = self.calculation_of_values_on_kohonen_layer(training_example)
            result_layer_grossberg = self.calculation_of_values_on_grossberg_layer(result_kohonen_layer, index_winning_neuron)
            predictions.append(result_layer_grossberg)
        return predictions



In [143]:
cp_neurons = CounterPropagation(kohonen_neurons=4,
                                grossberg_neurons=3,
                                epoch=100,
                                learning_rate_a=0.1,
                                learning_rate_b=0.1)

In [144]:
cp_neurons.train(X=X_train, y=y_train)

In [145]:
X_test_pred = cp_neurons.predict(X=X_train)
X_test_pred = bringing_the_response_back_to_normal(X_test_pred)
count_error(y_train, X_test_pred)

Mean Squared Error: 0.022222222222222223
R-squared: 0.8999999999999998
Mean Absolute Error: 0.022222222222222223


In [146]:
X_test_pred = cp_neurons.predict(X=X_test)
X_test_pred = bringing_the_response_back_to_normal(X_test_pred)
count_error(y_test, X_test_pred)

Mean Squared Error: 0.013333333333333334
R-squared: 0.9404761904761906
Mean Absolute Error: 0.013333333333333334
